SCENES = [
    {
        "id": "podcast",
        "name": "播客模式",
        "icon": "🎙️",
        "description": "轻松口语化风格，适合播客节目和访谈内容",
        "defaultSpeed": 1.1,
        "color": "#6366f1",
        "recommendedVoices": ["zh-CN-YunxiNeural", "zh-CN-XiaoyiNeural"],
    },
    {
        "id": "knowledge",
        "name": "知识讲解",
        "icon": "📚",
        "description": "正式专业风格，适合课程讲授和知识科普",
        "defaultSpeed": 0.95,
        "color": "#10b981",
        "recommendedVoices": ["zh-CN-XiaoxiaoNeural", "zh-CN-YunyangNeural"],
    },
    {
        "id": "story",
        "name": "故事叙述",
        "icon": "📖",
        "description": "富有表现力，适合故事、有声书和绘本朗读",
        "defaultSpeed": 1.0,
        "color": "#f59e0b",
        "recommendedVoices": ["zh-CN-YunxiNeural", "zh-CN-YunxiaNeural"],
    },
    {
        "id": "emotion",
        "name": "情感朗读",
        "icon": "💝",
        "description": "温婉细腻，适合散文、诗歌和情感类内容",
        "defaultSpeed": 0.9,
        "color": "#ec4899",
        "recommendedVoices": ["zh-CN-XiaoxiaoNeural", "zh-CN-XiaoyiNeural"],
    },
]

VOICES = [
    {
        "id": "zh-CN-XiaoxiaoNeural",
        "name": "晓晓",
        "gender": "female",
        "style": "温柔",
        "category": "知识类",
        "description": "温柔自然的女声，适合知识讲解、课程录制和散文朗读",
        "locale": "zh-CN",
        "isRecommended": True,
    },
    {
        "id": "zh-CN-XiaoyiNeural",
        "name": "晓伊",
        "gender": "female",
        "style": "活泼",
        "category": "情感类",
        "description": "活泼清亮的女声，适合轻松内容、情感表达和儿童故事",
        "locale": "zh-CN",
        "isRecommended": True,
    },
    {
        "id": "zh-CN-YunjianNeural",
        "name": "云健",
        "gender": "male",
        "style": "活力",
        "category": "播客类",
        "description": "充满力量感的男声，适合运动、户外和热血叙事",
        "locale": "zh-CN",
        "isRecommended": True,
    },
    {
        "id": "zh-CN-YunxiNeural",
        "name": "云希",
        "gender": "male",
        "style": "磁性",
        "category": "故事类",
        "description": "自然有表现力的男声，适合故事叙述和播客节目",
        "locale": "zh-CN",
        "isRecommended": True,
    },
    {
        "id": "zh-CN-YunxiaNeural",
        "name": "云夏",
        "gender": "male",
        "style": "童趣",
        "category": "故事类",
        "description": "偏童真可爱的男声，适合儿童绘本和轻松故事",
        "locale": "zh-CN",
        "isRecommended": False,
    },
    {
        "id": "zh-CN-YunyangNeural",
        "name": "云扬",
        "gender": "male",
        "style": "专业",
        "category": "知识类",
        "description": "稳定可靠的新闻播报感男声，适合正式内容和知识科普",
        "locale": "zh-CN",
        "isRecommended": True,
    },
    {
        "id": "zh-CN-liaoning-XiaobeiNeural",
        "name": "辽宁小北",
        "gender": "female",
        "style": "方言",
        "category": "播客类",
        "description": "辽宁方言女声，适合地域特色播客和轻松内容",
        "locale": "zh-CN-liaoning",
        "isRecommended": False,
    },
    {
        "id": "zh-CN-shaanxi-XiaoniNeural",
        "name": "陕西小妮",
        "gender": "female",
        "style": "方言",
        "category": "故事类",
        "description": "陕西方言女声，适合方言故事和地方文化内容",
        "locale": "zh-CN-shaanxi",
        "isRecommended": False,
    },
]

VOICE_BY_ID = {voice["id"]: voice for voice in VOICES}
SCENE_BY_ID = {scene["id"]: scene for scene in SCENES}
